   databases:
      - name: help_juice_articles_production
        databaseName: help_juice_articles_production
        user: help_juice_articles

   services:
      - type: web
        name: help_juice_articles
        env: ruby
        buildCommand: "./bin/render-build.sh"
        startCommand: "bundle exec puma -C config/puma.rb"
        envVars:
          - key: DATABASE_URL
            fromDatabase:
              name: help_juice_articles_production
              property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false